'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { challengeWorkflow } from '@/data/challengeWorkflow';
import { ArrowLeft, Check, ChevronRight, Copy, ImagePlus, Link2, Search, Send, ShieldCheck, Sparkles, Users, UserRound, Video } from 'lucide-react';

type Mode='direct'|'open'|null;
const categories=['Fashion','Photography','Music','Gaming','Sports','Lifestyle','Art','Food'];

export function CreateScreen(){
  const router=useRouter();
  const [step,setStep]=useState(1); const [mode,setMode]=useState<Mode>(null);
  const [title,setTitle]=useState(''); const [category,setCategory]=useState('Fashion');
  const [media,setMedia]=useState('https://picsum.photos/seed/my-side/900/1100'); const [mediaType,setMediaType]=useState<'image'|'video'>('image');
  const [opponent,setOpponent]=useState(''); const [published,setPublished]=useState(false); const [copied,setCopied]=useState(false);
  const [createdId,setCreatedId]=useState('');
  const createChallenge = () => { const id = `ch_${Date.now().toString(36)}`; challengeWorkflow.unshift({ id, title: title.trim(), category, creator: { name: 'You', username: 'you', image: 'https://picsum.photos/seed/you/200/200' }, opponent: mode === 'direct' ? { name: opponent, username: opponent, image: 'https://picsum.photos/seed/opponent/200/200' } : null, creatorSide: media, creatorMediaType: mediaType, creatorMediaUrl: mediaType === 'video' ? 'https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4' : undefined, creatorThumbnail: mediaType === 'video' ? 'https://picsum.photos/seed/my-video/900/1100' : undefined, opponentSide: null, visibility: mode === 'direct' ? 'direct' : 'open', status: mode === 'direct' ? 'opponent_invited' : 'waiting_for_opponent', votesA: 0, votesB: 0, endsAt: new Date(Date.now() + 24*60*60*1000).toISOString() }); setCreatedId(id); setPublished(true); };
  const canContinue=step===1?title.trim().length>=4:step===2?!!media:!!mode&&(mode==='open'||opponent.length>0);

  if(published)return <div className="flex h-full items-center justify-center overflow-y-auto bg-[radial-gradient(circle_at_top,#301238,#09090b_55%)] px-6 py-10"><div className="w-full max-w-sm text-center"><div className="mx-auto flex h-20 w-20 items-center justify-center rounded-full bg-pop-500/15 text-pop-300"><Check size={36}/></div><p className="mt-5 text-xs font-bold uppercase tracking-[0.2em] text-pop-300">{mode==='open'?'Challenge created':'Invitation sent'}</p><h1 className="mt-2 text-3xl font-black text-white">{mode==='open'?'Your arena is ready.':'Opponent invited.'}</h1><p className="mt-3 text-sm leading-6 text-white/50">{mode==='open'?'Share your link. The first person to join becomes your opponent.':'@'+opponent+' will add their side before the Challenge goes live.'}</p><div className="mt-7 space-y-3"><button onClick={()=>router.push('/challenge/'+createdId+'/status')} className="w-full rounded-2xl bg-white py-3.5 text-sm font-black text-black">Open Challenge Status</button>{mode==='open'&&<button onClick={()=>{if(navigator.clipboard)navigator.clipboard.writeText(window.location.origin+'/challenge/'+createdId);setCopied(true);setTimeout(()=>setCopied(false),1400)}} className="flex w-full items-center justify-center gap-2 rounded-2xl bg-white/5 py-3.5 text-sm font-bold text-white">{copied?<Check size={16}/>:<Copy size={16}/>} {copied?'Link copied':'Copy invite link'}</button>}<button onClick={()=>router.push('/')} className="w-full rounded-2xl bg-white/5 py-3.5 text-sm font-bold text-white">Back home</button></div></div></div>;

  return <div className="h-full overflow-y-auto bg-[#09090b] pb-28">
    <header className="sticky top-0 z-20 border-b border-white/[0.06] bg-black/75 px-4 py-4 backdrop-blur-xl"><div className="flex items-center gap-3"><button onClick={()=>step===1?router.back():setStep(step-1)} className="rounded-full bg-white/5 p-2 text-white/70"><ArrowLeft size={18}/></button><div className="flex-1"><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-white/35">Create Challenge</p><h1 className="text-lg font-black text-white">{step===1?'Set the question':step===2?'Add your side':'Choose your opponent'}</h1></div><span className="text-xs font-bold text-white/30">{step}/3</span></div><div className="mt-3 h-1 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-gradient-to-r from-pop-500 to-neon-500" style={{width:(step*33.33)+'%'}}/></div></header>
    <main className="space-y-5 px-4 pt-5">
      {step===1&&<><section className="rounded-3xl border border-white/10 bg-white/[0.035] p-5"><div className="mb-4 flex h-11 w-11 items-center justify-center rounded-2xl bg-pop-500/15 text-pop-300"><Sparkles size={21}/></div><label className="text-xs font-bold uppercase tracking-[0.15em] text-white/40">Your question</label><textarea value={title} onChange={e=>setTitle(e.target.value)} maxLength={80} placeholder="Who has the better style?" className="mt-3 h-28 w-full resize-none bg-transparent text-2xl font-black leading-tight text-white outline-none placeholder:text-white/20"/><div className="text-right text-[10px] text-white/25">{title.length}/80</div></section><section><p className="mb-3 text-xs font-bold uppercase tracking-[0.15em] text-white/40">Category</p><div className="flex flex-wrap gap-2">{categories.map(cat=><button key={cat} onClick={()=>setCategory(cat)} className={['rounded-full px-4 py-2 text-xs font-bold',category===cat?'bg-white text-black':'bg-white/5 text-white/55'].join(' ')}>{cat}</button>)}</div></section></>}
      {step===2&&<><section className="overflow-hidden rounded-3xl border border-white/10 bg-white/[0.035]"><div className="aspect-[4/5] overflow-hidden bg-black">{mediaType === "video" ? <video src="https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4" poster={media} muted loop autoPlay playsInline className="h-full w-full object-cover" /> : <img src={media} alt="Your challenge side" className="h-full w-full object-cover"/>}</div><div className="p-4"><p className="text-xs font-bold uppercase tracking-[0.15em] text-pop-300">Your side</p><p className="mt-1 text-lg font-black text-white">This is what voters will compare.</p><div className="mt-3 grid grid-cols-2 gap-2"><button onClick={()=>{setMediaType("image");setMedia("https://picsum.photos/seed/side-"+Date.now()+"/900/1100")}} className={`flex items-center justify-center gap-2 rounded-xl px-3 py-2 text-xs font-bold ${mediaType==="image"?"bg-white text-black":"bg-white/5 text-white/70"}`}><ImagePlus size={15}/> Photo</button><button onClick={()=>{setMediaType("video");setMedia("https://picsum.photos/seed/my-video/900/1100")}} className={`flex items-center justify-center gap-2 rounded-xl px-3 py-2 text-xs font-bold ${mediaType==="video"?"bg-pop-500 text-white":"bg-white/5 text-white/70"}`}><Video size={15}/> Video</button></div></div></section><div className="flex gap-3 rounded-2xl border border-white/10 bg-white/[0.025] p-4"><ShieldCheck size={18} className="shrink-0 text-emerald-400"/><p className="text-xs leading-5 text-white/45">Your opponent adds their own media. You never need to upload both sides yourself.</p></div></>}
      {step===3&&<><section className="space-y-3"><button onClick={()=>setMode('direct')} className={['flex w-full items-center gap-4 rounded-3xl border p-5 text-left',mode==='direct'?'border-pop-400/60 bg-pop-500/10':'border-white/10 bg-white/[0.035]'].join(' ')}><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-white/5"><UserRound size={22} className="text-white/70"/></div><div className="flex-1"><p className="font-black text-white">Challenge someone</p><p className="mt-1 text-xs leading-5 text-white/40">Pick a friend or creator you want to face.</p></div>{mode==='direct'?<Check size={19} className="text-pop-300"/>:<ChevronRight size={19} className="text-white/25"/>}</button><button onClick={()=>setMode('open')} className={['flex w-full items-center gap-4 rounded-3xl border p-5 text-left',mode==='open'?'border-neon-400/60 bg-neon-500/10':'border-white/10 bg-white/[0.035]'].join(' ')}><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-white/5"><Link2 size={22} className="text-white/70"/></div><div className="flex-1"><p className="font-black text-white">Open Challenge</p><p className="mt-1 text-xs leading-5 text-white/40">Share a link. The first person who joins becomes your opponent.</p></div>{mode==='open'?<Check size={19} className="text-neon-300"/>:<ChevronRight size={19} className="text-white/25"/>}</button></section>
      {mode==='direct'&&<section className="rounded-3xl border border-white/10 bg-white/[0.035] p-4"><label className="flex items-center gap-2 text-xs font-bold uppercase tracking-[0.15em] text-white/40"><Search size={14}/> Find opponent</label><input value={opponent} onChange={e=>setOpponent(e.target.value.replace('@',''))} placeholder="username" className="mt-3 w-full rounded-2xl border border-white/10 bg-black/30 px-4 py-3 text-sm font-bold text-white outline-none"/></section>}
      {mode==='open'&&<div className="rounded-3xl border border-neon-400/20 bg-neon-500/5 p-5"><div className="flex items-start gap-3"><Users size={18} className="mt-0.5 text-neon-300"/><div><p className="font-bold text-white">No opponent? No problem.</p><p className="mt-1 text-xs leading-5 text-white/45">Your Challenge waits until someone joins. Share it anywhere to find your opponent.</p></div></div></div>}</>}
      <button disabled={!canContinue} onClick={()=>step<3?setStep(step+1):createChallenge()} className="flex w-full items-center justify-center gap-2 rounded-2xl bg-white py-4 text-sm font-black text-black disabled:opacity-25">{step<3?<>Continue <ChevronRight size={17}/></>:mode==='open'?<>Create & Share <Send size={16}/></>:<>Send Challenge <Send size={16}/></>}</button>
    </main>
  </div>;
}
